### ISSUE TITLE
Update api helm source chart to use stateless-srv

### ISSUE THREAD

**Issue by justincorrigible** [supercluster-covid-data-portal/api#10]
Rough description of the process for this task:

- [x] 1. clone `stateless-svc` from icgc-argo into overture helm charts repo.
---
- [x] 2. customise missing parametres to ensure compatibility with arranger + api needs
---
- [x] 3. update terraform and helm values in supercluster infra repo
---
- [x] 4. test it deploys correctly
---
- [x] 5. repeat 2-4 until success...

**Comment by justincorrigible** [comment]
Success came at the eleventh hour. All changes have been documented in the `supercluster/infra` repo, in the api helm+terraform charts.

**Comment by b-f-chan** [comment]
Tested successfully on DEV, the fact that the portal is running and I can make queries is proof enough that the API is deployed and running. Ready for release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
