### ISSUE TITLE
Implement "query storage" middleware

### ISSUE THREAD

**Issue by justincorrigible** [supercluster-covid-data-portal/api#4]
After studying the available DNAStack endpoints for user storage, we've determined a middleware layer should be implemented in our API, roughly described as follows:

METHOD `/api/storage/{endpoint}` (description):
 * GET /query (get a list of all queries for the current user)
 * GET /query/{id} (gets an individual query by its ID)
 * POST /query (stores a query, and responds with the corresponding ID)
 * PUT /query/{id} (update if exist) idempotent
 * DELETE /query/{id} (self-explainatory if exists)
 * DELETE /query/all (delete all) (self-explainatory)

Will amend this while on break...

**Comment by b-f-chan** [comment]
Deployed to DEV.  Tested successfully as queries can be saved and loaded from storage.  Other query tests will be done in separate tickets.  Moving this ticket to awaiting release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
