### ISSUE TITLE
Read Secrets from Vault

### ISSUE THREAD

**Issue by joneubank** [supercluster-covid-data-portal/api#9]
Modify config to have a `getSecrets()` method that will return the secret values stored in vault.

Will need to add environment variables to connect to and read from vault.

As a model for how to do this:
https://github.com/icgc-argo/files-service/blob/develop/src/external/vault.ts
https://github.com/icgc-argo/files-service/blob/develop/src/config.ts#L96

This service needs to read from vault:
- DNAStack client secret

**Comment by b-f-chan** [comment]
Tested successfully on DEV, the fact that I can correctly login into the portal via DNAstack wallet and my Google provider is proof enough that this works.  Ready for release.

**Comment by b-f-chan** [comment]
Deployed and tested successfully in prod, closing
